

### Get Access Token with Password and Username
POST https://2censored*trial.authentication.eu10.hana.ondemand.com/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=*your username, in scp trial your email*
&password=*your user password*
&scope=
&client_id=*your client id*
&client_secret=*your client secret*


###
GET cf-node-xsuaa-v1.cfapps.eu10.hana.ondemand.com
Authorization: Bearer ey....43t5z45wj763j7646j4778k75k578k5879k588857k57k


###
GET https://host:port/auth-info HTTP/1.1
Authorization: Bearer ey....43t5z45wj763j7646j4778k75k578k5879k588857k57k

